-- PRACTICE PROBLEMS
-- problem 1
select CUSTNO,CUSTNAME,PHONE,CITY from CUSTOMER;
-- problem 2
select CUSTNO,CUSTNAME,PHONE,CITY from CUSTOMER
where STATE='CO';
-- problem 3
select * from EVENTREQUEST
where ESTCOST > 4000
order by DATEHELD;
-- problem 4
select EVENTNO,DATEHELD,ESTAUDIENCE from EVENTREQUEST
where (STATUS='Approved' AND ESTAUDIENCE > 9000) OR (STATUS='Pending' AND ESTAUDIENCE > 7000);
-- problem 5
select EVENTNO,DATEHELD,CUSTOMER.CUSTNO,CUSTNAME, CITY 
from EVENTREQUEST,CUSTOMER
WHERE City = 'Boulder' 
        AND DateHeld BETWEEN '2018-12-01'AND '2018-12-31'
        AND EVENTREQUEST.CUSTNO = CUSTOMER.CUSTNO;
-- problem 6
select PLANNO, AVG(NUMBERFLD) as AVGNUMRES
from EVENTPLANLINE
where LOCNO='L100' 
group by PLANNO;
-- problem 7
select PLANNO, LOCNO, count(LINENO) as NUMLINES, AVG(NUMBERFLD) as AVGNUMRES
from EVENTPLANLINE
where LOCNO='L100'
group by PLANNO
having count(LINENO) > 1;


-- ASSIGNMENT PROBLEMS
-- problem 1
select distinct CITY, STATE,ZIP 
from CUSTOMER;
-- problem 2
SELECT EMPNAME, DEPARTMENT,PHONE,EMAIL
FROM EMPLOYEE
WHERE PHONE LIKE '3-%';

-- problem 3
select  *
from RESOURCETBL
where RATE >= 10 and RATE <=20
order by RATE DESC;

-- problem 4
SELECT EVENTNO,DATEAUTH,STATUS
FROM EVENTREQUEST
WHERE
        (DATEAUTH BETWEEN '2018-07-01' AND '2018-07-31') AND
        (STATUS = 'Approved' OR STATUS='DENIED');

-- problem 5
SELECT LOCNO,LOCNAME
FROM LOCATION,FACILITY
WHERE LOCATION.FACNO=FACILITY.FACNO AND
FACILITY.FACNAME="Basketball arena";

-- problem 6
SELECT  PLANNO,COUNT(LINENO) as NUMLINES,SUM(NUMBERFLD) AS SUMRES
from EVENTPLANLINE
GROUP BY PLANNO;
-- HAVING NUMLINES > 3;