-- Graded Problems for Module 5
-- problem 1
SELECT
  EVENTREQUEST.EVENTNO,
  DATEHELD,
  COUNT(*) as NUMEVENTS
FROM EVENTREQUEST,
  EVENTPLAN,
  EVENTPLANLINE
WHERE
  EVENTREQUEST.EVENTNO = EVENTPLAN.EVENTNO
  AND EVENTPLAN.PLANNO = EVENTPLANLINE.PLANNO
  AND (
    EVENTPLAN.WORKDATE BETWEEN '2018-12-01'
    AND '2018-12-31'
  )
GROUP BY
  EVENTPLANLINE.PLANNO
HAVING
  NUMEVENTS > 1;