-- Graded Problems for Module 5
-- problem 1
SELECT
  EVENTREQUEST.EVENTNO,
  DATEHELD,
  COUNT(*) as NUMEVENTS
FROM EVENTREQUEST,
  EVENTPLAN,
  EVENTPLANLINE
WHERE
  EVENTREQUEST.EVENTNO = EVENTPLAN.EVENTNO
  AND EVENTPLAN.PLANNO = EVENTPLANLINE.PLANNO
  AND (
    EVENTPLAN.WORKDATE BETWEEN '2018-12-01'
    AND '2018-12-31'
  )
GROUP BY
  EVENTPLANLINE.PLANNO
HAVING
  NUMEVENTS > 1;
-- problem 2
SELECT
  DISTINCT EVENTPLAN.PLANNO,
  EVENTNO,
  WORKDATE,
  ACTIVITY
FROM EVENTPLAN,
  EVENTPLANLINE,
  LOCATION,
  FACILITY
WHERE
  EVENTPLAN.PLANNO = EVENTPLANLINE.PLANNO
  AND EVENTPLANLINE.LOCNO = LOCATION.LOCNO
  AND LOCATION.FACNO = FACILITY.FACNO
  AND WORKDATE BETWEEN '2018-12-01'
  AND '2018-12-31'
  AND FACNAME = "Basketball Arena";
-- problem 3
SELECT
  DISTINCT EVENTPLAN.EVENTNO,
  DATEHELD,
  STATUS,
  ESTCOST -- EMPNAME,
  -- FACNAME
FROM EVENTREQUEST,
  EVENTPLAN,
  EMPLOYEE,
  EVENTPLANLINE,
  LOCATION,
  FACILITY
WHERE
  EVENTPLAN.EVENTNO = EVENTREQUEST.EVENTNO
  AND EVENTPLAN.EMPNO = EMPLOYEE.EMPNO
  AND EVENTPLAN.PLANNO = EVENTPLANLINE.PLANNO
  AND EVENTPLANLINE.LOCNO = LOCATION.LOCNO
  AND LOCATION.FACNO = FACILITY.FACNO
  AND EMPNAME = "Mary Manager"
  AND WORKDATE BETWEEN '2018-10-01'
  AND '2018-12-31'
  AND FACNAME = "Basketball Arena";
-- problem 4
SELECT
  EVENTPLANLINE.PLANNO,
  LINENO,
  RESNAME,
  NUMBERFLD,
  LOCNAME,
  TIMESTART,
  TIMEEND -- FACNAME,
  -- ACTIVITY,
  -- WORKDATE
FROM EVENTPLANLINE,
  LOCATION,
  FACILITY,
  EVENTPLAN,
  RESOURCETBL
WHERE
  EVENTPLANLINE.LOCNO = LOCATION.LOCNO
  AND EVENTPLAN.PLANNO = EVENTPLANLINE.PLANNO
  AND EVENTPLANLINE.LOCNO = LOCATION.LOCNO
  AND EVENTPLANLINE.RESNO = RESOURCETBL.RESNO
  AND LOCATION.FACNO = FACILITY.FACNO
  AND FACNAME = "Basketball Arena"
  AND ACTIVITY = "Operation"
  AND WORKDATE BETWEEN '2018-10-01'
  AND '2018-12-31';
-- DATABASE MOD PROBLEMS
  -- P1
INSERT INTO FACILITY
VALUES
  ('F104', 'Swimming Pool');
-- SELECT
  --   *
  -- from FACILITY;
  -- P2
INSERT INTO LOCATION
VALUES
  ('L107', 'F104', 'Door');
-- SELECT
  --   *
  -- from LOCATION;
INSERT INTO LOCATION
VALUES
  ('L108', 'F104', 'Locker Room');
UPDATE LOCATION
SET
  LOCNAME = 'Gate'
WHERE
  LOCNAME = 'Door'
  AND LOCNO = 'L107';
DELETE FROM LOCATION
WHERE
  LOCNO = 'L107';