create TABLE customer
(
    CUSTNO CHAR(4) NOT NULL PRIMARY KEY,
    CUSTNAME VARCHAR(50) NOt NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    INTERNAL CHAR(1) NOT NULL,
    CONTACT VARCHAR(50) NOT NULL,
    PHONE CHAR(7) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE CHAR(2) NOT NULL,
    ZIP CHAR(6) NOT NULL
);
create TABLE FACILITY
(
    FACNO CHAR(4) NOT NULL PRIMARY KEY,
    FACNAME VARCHAR(50) NOT NULL
);
create TABLE LOCATION
(
    LOCNO CHAR(4) NOT NULL PRIMARY KEY,
    FACNO CHAR(4) NOT NULL,
    FOREIGN KEY (FACNO) REFERENCES FACILITY(FACNO),
    LOCNAME VARCHAR(50) NOT NULL
)