create TABLE CUSTOMER (
    CUSTNO CHAR(4) NOT NULL PRIMARY KEY,
    CUSTNAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    INTERNAL CHAR(1) NOT NULL,
    CONTACT VARCHAR(50) NOT NULL,
    PHONE CHAR(7) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE CHAR(2) NOT NULL,
    ZIP CHAR(6) NOT NULL
);

create TABLE FACILITY (
    FACNO CHAR(4) NOT NULL PRIMARY KEY,
    FACNAME VARCHAR(50) NOT NULL
);

create TABLE LOCATION (
    LOCNO CHAR(4) NOT NULL PRIMARY KEY,
    FACNO CHAR(4) NOT NULL,
    FOREIGN KEY (FACNO) REFERENCES FACILITY(FACNO),
    LOCNAME VARCHAR(50) NOT NULL
);

create TABLE EMPLOYEE (
    EMPNO CHAR(4) NOT NULL PRIMARY KEY,
    EMPNAME VARCHAR(50) NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PHONE CHAR(6) NOT NULL
);

create TABLE RESOURCETBL (
    RESNO CHAR(4) NOT NULL PRIMARY KEY,
    RESNAME VARCHAR(50) NOT NULL,
    RATE INT NOT NULL,
    CHECK (RATE > 0)
);

create TABLE EVENTREQUEST (
    EVENTNO CHAR(4) NOT NULL PRIMARY KEY,
    DATEHELD DATE NOT NULL,
    DATEREQ DATE NOT NULL,
    CUSTNO CHAR(4) NOT NULL,
    FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER(CUSTNO),
    FACNO CHAR(4) NOT NULL,
    FOREIGN KEY (FACNO) REFERENCES FACILITY(FACNO),
    DATEAUTH DATE,
    STATUS VARCHAR(50) NOT NULL,
    ESTCOST INT NOT NULL,
    ESTAUDIENCE INT NOT NULL,
    BUDNO CHAR(5),
    CHECK (STATUS IN ('Approved', 'Denied', 'Pending')),
    CHECK (ESTAUDIENCE > 0)
);

create TABLE EVENTPLAN (
    PLANNO CHAR(4) NOT NULL PRIMARY KEY,
    EVENTNO CHAR(4) NOT NULL,
    FOREIGN KEY (EVENTNO) REFERENCES EVENTREQUEST(EVENTNO),
    WORKDATE DATE NOT NULL,
    NOTES VARCHAR(50),
    ACTIVITY VARCHAR(50) NOT NULL,
    EMPNO CHAR(4),
    FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE(EMPNO)
);

create TABLE EVENTPLANLINE (
    PLANNO CHAR(4) NOT NULL,
    FOREIGN KEY (PLANNO) REFERENCES EVENTPLAN(PLANNO),
    LINENO INT NOT NULL,
    PRIMARY KEY(PLANNO, LINENO),
    TIMESTART DATETIME NOT NULL,
    TIMEEND DATETIME NOT NULL,
    NUMBERFLD INT NOT NULL,
    LOCNO CHAR(4) NOT NULL,
    FOREIGN KEY (LOCNO) REFERENCES LOCATION(LOCNO),
    RESNO CHAR(4) NOT NULL,
    FOREIGN KEY (RESNO) REFERENCES RESOURCETBL(RESNO),
    CHECK (TIMEEND > TIMESTART)
)