CREATE TABLE EMPLOYEEWITHSUP (
  EMPID INT NOT NULL PRIMARY KEY,
  EMPSUPERVISORID int,
  FOREIGN key (EMPSUPERVISORID) REFERENCES EMPLOYEE(EMPID),
  EMPFIRSTNAME VARCHAR(255) NOT NULL,
  EMPLASTNAME VARCHAR(255) NOT NULL,
  EMPPHONE VARCHAR(255) NOT NULL,
  EMPEMAIL VARCHAR(255) NOT NULL,
  EMPDEPTNAME VARCHAR(255) NOT NULL,
  EMPCOMMRATE NUMERIC NOT NULL
);
CREATE TABLE ORDERTABLE (
  ORDNO INT NOT NULL PRIMARY KEY,
  EMPID INT,
  ORNAME VARCHAR(255) NOT NULL,
  ORDATE DATE NOT NULL,
  ORDADDRESS VARCHAR(255) NOT NULL,
  FOREIGN KEY (EMPID) REFERENCES EMPLOYEE(EMPID)
);
CREATE TABLE PRODUCTTABLE (
  PRODNO INT NOT NULL PRIMARY KEY,
  PRODNAME VARCHAR(255) NOT NULL,
  PRODPRICE NUMERIC NOT NULL
);
CREATE TABLE ORDERPRODUCT (
  ORDNO INT NOT NULL,
  PRODNO INT NOT NULL,
  PRIMARY KEY (ORDNO, PRODNO),
  FOREIGN KEY (ORDNO) REFERENCES ORDERTABLE(ORDNO),
  FOREIGN KEY (PRODNO) REFERENCES PRODUCTTABLE(PRODNO)
);
CREATE TABLE ORDERLINE (
  ID INT PRIMARY KEY,
  QTY INT NOT NULL,
  ORDNO INT NOT NULL,
  PRODNO INT,
  FOREIGN KEY (ORDNO) REFERENCES ORDERTABLE(ORDNO),
  FOREIGN KEY (PRODNO) REFERENCES PRODUCTTABLE(PRODNO)
);